import torch
import torch as th
from torch import nn
from torch.func import functional_call
from functools import partial
from typing import List
from tqdm import tqdm
from train_utils import Posterior_Coefficients, sample_posterior_combine

# --- MLP for Hyper-network (Adapted from HyperDM) ---
# This network will generate the weights for the main diffusion models.

class MLP(th.nn.Module):
    """A simple Multi-Layer Perceptron to be used as a hyper-network."""
    def __init__(self, layer_channels: List[int]):
        super(MLP, self).__init__()

        layers = []
        for i in range(len(layer_channels) - 2):
            layers.append(nn.Linear(layer_channels[i], layer_channels[i + 1]))
            layers.append(nn.ReLU())
        # Append output layer
        layers.append(nn.Linear(layer_channels[-2], layer_channels[-1]))
        self.mlp = nn.Sequential(*layers)

    def forward(self, x):
        """
        Takes a noise vector `z` and outputs the flattened weights for a primary network.
        """
        return self.mlp(x)

# --- HyperDM Wrapper for MU-Diff Architecture ---

class HyperDM_MU_Diff(th.nn.Module):
    """
    A wrapper that applies the Hyper-Diffusion uncertainty estimation technique
    to the MU-Diff architecture.
    """
    def __init__(self, primary_net1: th.nn.Module, primary_net2: th.nn.Module,
                 hyper_net1_dims: List[int], hyper_net2_dims: List[int],
                 diffusion_args, pos_coeff: Posterior_Coefficients):
        """
        Initializes the HyperDM wrapper for the two MU-Diff generator networks.

        :param primary_net1: The first generator network (gen_diffusive_1, NCSNpp).
        :param primary_net2: The second generator network (gen_diffusive_2, NCSNpp_adaptive).
        :param hyper_net1_dims: A list of integers defining the layer dimensions for the first hyper-network.
        :param hyper_net2_dims: A list of integers defining the layer dimensions for the second hyper-network.
        :param diffusion_args: The argument namespace from your train/test script, needed for sampling parameters like `nz` and `num_timesteps`.
        :param pos_coeff: An instance of your `Posterior_Coefficients` class from `train.py`.
        """
        super().__init__()

        self.primary_net1 = primary_net1
        self.primary_net2 = primary_net2
        self.args = diffusion_args
        self.pos_coeff = pos_coeff

        # Calculate the total number of parameters for each primary network
        self.primary1_params_count = sum(p.numel() for p in self.primary_net1.parameters())
        self.primary2_params_count = sum(p.numel() for p in self.primary_net2.parameters())

        # Freeze the parameters of the primary networks as they will be set by the hyper-networks
        for param in self.primary_net1.parameters():
            param.requires_grad = False
        for param in self.primary_net2.parameters():
            param.requires_grad = False

        # Define the hyper-networks that will generate the weights
        hyper_net1_dims.append(self.primary1_params_count)
        self.hyper_net1_input_dim = hyper_net1_dims[0]
        self.hyper_net1 = MLP(hyper_net1_dims)

        hyper_net2_dims.append(self.primary2_params_count)
        self.hyper_net2_input_dim = hyper_net2_dims[0]
        self.hyper_net2 = MLP(hyper_net2_dims)

        self.hyper1_params_count = sum(p.numel() for p in self.hyper_net1.parameters())
        self.hyper2_params_count = sum(p.numel() for p in self.hyper_net2.parameters())

    def print_stats(self):
        """Prints the parameter counts for the networks."""
        print(f"# of params (Primary Net 1): {self.primary1_params_count}")
        print(f"# of params (Hyper Net 1):   {self.hyper1_params_count}")
        print(f"# of params (Primary Net 2): {self.primary2_params_count}")
        print(f"# of params (Hyper Net 2):   {self.hyper2_params_count}")

    def sample_networks(self, device=None):
        """
        Samples two functional networks with weights generated by the hyper-networks.

        :param device: The device to run the models on.
        :return: A tuple of two callable functional models (func_net1, func_net2).
        """
        # --- Sample weights for the first network ---
        z1 = th.randn(self.hyper_net1_input_dim, device=device)
        weights1_flat = self.hyper_net1(z1).ravel()
        
        weight_dict1 = {}
        i = 0
        for name, param in self.primary_net1.named_parameters():
            num_params = param.numel()
            weight_dict1[name] = weights1_flat[i:i + num_params].view(param.shape)
            i += num_params
        
        func_net1 = partial(th.func.functional_call, self.primary_net1, weight_dict1)

        # --- Sample weights for the second network ---
        z2 = th.randn(self.hyper_net2_input_dim, device=device)
        weights2_flat = self.hyper_net2(z2).ravel()

        weight_dict2 = {}
        i = 0
        for name, param in self.primary_net2.named_parameters():
            num_params = param.numel()
            weight_dict2[name] = weights2_flat[i:i + num_params].view(param.shape)
            i += num_params
            
        func_net2 = partial(th.func.functional_call, self.primary_net2, weight_dict2)

        return func_net1, func_net2

    def forward(self, x_tp1, cond1, cond2, cond3, t):
        """
        Performs a single forward pass for training. It samples networks and computes
        the denoised predictions x_0. The full loss (adv, L1, etc.) is computed in the main training loop.
        """
        device = x_tp1.device
        batch_size = x_tp1.shape[0]
        latent_z = th.randn(batch_size, self.args.nz, device=device)

        # Sample functional networks
        func_net1, func_net2 = self.sample_networks(device=device)

        # Get predictions using the functional models
        x0_pred1 = func_net1((x_tp1, cond1, cond2, cond3, t, latent_z))
        x0_pred2 = func_net2((x_tp1, cond1, cond2, cond3, t, latent_z, x0_pred1[:, [0], :]))
        
        return x0_pred1, x0_pred2

    @torch.no_grad()
    def get_mean_variance(self, M: int, N: int, cond1, cond2, cond3, x_init, device=None, progress=False):
        """
        Samples the predictive distribution to estimate aleatoric and epistemic uncertainty.
        This is designed for testing/inference.

        :param M: Number of network weight sets to sample (for epistemic uncertainty).
        :param N: Number of predictions to generate per weight set (for aleatoric uncertainty).
        :param cond1, cond2, cond3: Conditional inputs for the MU-Diff model.
        :param x_init: Initial noise tensor for the diffusion process.
        :param device: The device to run inference on.
        :param progress: Whether to show a tqdm progress bar.
        :return: A tuple (epistemic_uncertainty, aleatoric_uncertainty, mean_prediction).
        """
        self.eval()
        
        all_preds = []
        M_range = tqdm(range(M), desc="Epistemic Sampling (M)") if progress else range(M)
        
        for _ in M_range:
            # 1. Sample a new set of network weights
            func_net1, func_net2 = self.sample_networks(device)

            # 2. Generate N predictions for this set of weights
            preds_for_m = []
            for _ in range(N):
                # This function is from the MU-Diff test script, adapted to take functional models
                fake_sample = self._sample_from_functional_model(
                    self.pos_coeff, func_net1, cond1, func_net2, cond2, cond3,
                    self.args.num_timesteps, x_init, self.args, device
                )
                preds_for_m.append(fake_sample)
            
            all_preds.append(torch.stack(preds_for_m))
        
        all_preds_tensor = torch.stack(all_preds) # Shape: [M, N, C, H, W]

        # Calculate mean prediction (average over all M*N samples)
        mean_prediction = torch.mean(all_preds_tensor, dim=(0, 1))

        # Calculate Aleatoric Uncertainty: Mean of variances over N
        # Var_{j \in N}[preds] -> shape [M, C, H, W]
        # E_{i \in M}[Var_{j \in N}[preds]] -> shape [C, H, W]
        aleatoric_uncertainty = torch.mean(torch.var(all_preds_tensor, dim=1), dim=0)

        # Calculate Epistemic Uncertainty: Variance of means over N
        # E_{j \in N}[preds] -> shape [M, C, H, W]
        # Var_{i \in M}[E_{j \in N}[preds]] -> shape [C, H, W]
        epistemic_uncertainty = torch.var(torch.mean(all_preds_tensor, dim=1), dim=0)

        return epistemic_uncertainty, aleatoric_uncertainty, mean_prediction

    @torch.no_grad()
    def _sample_from_functional_model(self, coefficients, generator1, cond1, generator2, cond2, cond3, n_time, x_init, opt, device):
        """
        Internal sampling loop adapted from MU-Diff's `test.py` to work with functional models.
        """
        x = x_init
        
        for i in reversed(range(n_time)):
            t = torch.full((x.size(0),), i, dtype=torch.int64).to(device)
            latent_z = torch.randn(x.size(0), opt.nz, device=device)
            
            # Use functional calls here
            x_0_1 = generator1((x, cond1, cond2, cond3, t, latent_z))
            x_0_2 = generator2((x, cond1, cond2, cond3, t, latent_z, x_0_1[:, [0], :]))
            
            x_new = sample_posterior_combine(coefficients, x_0_1[:, [0], :], x_0_2[:, [0], :], x, t)
            x = x_new.detach()
            
        return x
